mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('explore/', include('research.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('upload/', views.upload, name='upload'),
    # path('login', views.login, name='login'),
    # path('signup', views.signup, name='signup'),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/research/urls.py
from django.urls import path
from . import views

app_name = 'research'
urlpatterns = [
    # ex: /explore/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /explore/5/
    path('upload/', views.UploadView.as_view(), name='upload'),
    # ex: /explore/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/research/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Study(models.Model):
    ACCESS_LEVEL = (
        ('public', 'Open&Free = is or could be made publicly available to all without restrictions'),
        ('restricted-public', 'Available, with some rules = available under certain use restrictions'),
        ('non-public', 'Private  = not available to members of the public'),
        )
    LANGUAGE = (
        ('English', 'English'),
        ('French', 'Français'),
        ('Italian', 'Italiano'),
        ('Spanish', 'Español'),
        )
    title = models.CharField(max_length=254)
    description = models.TextField()
    # tags = need to figure out if using taggit, many-to-many, or arrayfield
    pub_date = models.DateTimeField('date published')
    last_update = models.DateField(auto_now=True)
    publisher = models.CharField(max_length=254)
    contactPoint = models.CharField(max_length=254)
    mbox = models.EmailField(max_length=254)
    identifier = models.CharField(max_length=254)
    accessLevel = models.CharField(max_length=10, choices=ACCESS_LEVEL, default="public")
    landingPage = models.URLField(max_length=200)
    language = models.CharField(max_length=30, choices=LANGUAGE, default="English")
    issued = models.DateField(auto_now=False, auto_now_add=False)
    date_uploaded = models.DateTimeField(auto_now_add=True)
    document = models.FileField(upload_to='documents/')
    times_seen = models.IntegerField(default=0)
    def __str__(self):
        return 'Study #{}'.format(self.id)

    class Meta:
        verbose_name_plural = 'studies'

    def __str__(self):
        return self.title
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

   # def total_times_seen(self):
   #     return times_seen =+ 1

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]
        

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/research/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Study

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'research/index.html'
    context_object_name = 'latest_research_list'

    def get_queryset(self):
        """
        Return the last five published (not including those set to be
        published in the future).
        """
        return Study.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]
        

class DetailView(generic.DetailView):
    model = Study
    template_name = 'research/detail.html'

   # study = get_object_or_404(Study, id=pk)
   # study.add_seen()

class UploadView(generic.UploadView):
    model = Study
    template_name = 'research/upload.html'

class ResultsView(generic.DetailView):
    model = Study
    template_name = 'research/results.html'



       # selected_study.times_seen += 1
       # selected_study.save()

mysite/polls/templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}


<h1 class="title is-1">{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
<br>
{% endfor %}
<input class="button is-primary" type="submit" value="Vote">
</form>

{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'base.html' %}
{% block content %}




{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}
</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls available.</p>
{% endif %}

{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}


<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
    
<a href="{% url 'polls:index' %}">More polls?</a>

{% endblock %}

mysite/research/templates/research/detail.html
{% extends 'base.html' %}
{% block content %} </br>

<div class="columns">
    <div class="column is-two-thirds">
<div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
              <h1 class="title is-3">{{ study.title }}</h1>
              <p>
                <small>{{ study.publisher }}</small> <small>{{ research.attr }}</small>
                <br>
                <h2 class="title is-5">Abstract</h2>
                {{ study.description }}
              </p>
            </div>
            
            <object data='#url' type='application/pdf' width='100%' height='100%'>
              <p>This browser does not support inline PDFs. Please download the PDF to view it: <a href="#url">Download PDF</a></p>
            </object>
            
            <nav class="level is-mobile">
              <div class="level-left">
                <a class="level-item" aria-label="reply">
                  📝
                </a>
                <a class="level-item" aria-label="save">
                  📌
                </a>
                <a class="level-item" aria-label="tweet">
                  ✉️
                </a>
              </div>
            </nav>
          </div>
        </article>
      </div>
      <div class="box">
          <h3 class="title is-5">Take Notes/Make Inferences</h3>
          <p>(🛠Coming Soon🛠)</p>
        </div>
    </div>
    <div class="column">
        <div class="box">
            <h3 class="title is-5">Tweet This! 🐦</h3>
            <p>"Awesome quote from study" (🛠Coming Soon🛠)</p>
          </div>
        <div class="box">
            <h3 class="title is-5">TL;DR</h3>
            <p>cliff notes of the study (🛠Coming Soon🛠)</p>
          </div>
      <div class="box">
        <h3 class="title is-5">Citations</h3>
            <div class="box">
                <h4 class="subtitle is-6">AMA</h3>
                  <p>name, name. title year publisher stuffs and maybe the website junk (🛠Coming Soon🛠)</p>
              </div>
              <div class="box">
                  <h4 class="subtitle is-6">Chicago</h3>
                    <p>name, name. title year publisher stuffs and maybe the website junk (🛠Coming Soon🛠)</p>
                </div>
      </div>
      <div class="box">
        <h3 class="title is-5">Open Stats</h3>
        <p>(🛠Coming Soon🛠)</p>
        <p>{{ study.times_seen }} views</p>
      </div>
    </div>
  </div>





{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

</br>
{% endblock %}

mysite/research/templates/research/index.html
{% extends 'base.html' %}
{% block content %}

</br>
<div class="columns">
    <div class="column">
        <h2 class="title is-3">See</h2>
            <h4 class="subtitle is-5">recently uploaded studies</h4>
            {% if latest_research_list %}
            {% for research in latest_research_list %}
                    <div class="box">
                        <div class="tags are-medium">    
                            <span class="tag is-light">🌍🌎🌏 Climate </span>
                            <span class="tag is-info">🤓📖 Peer-Reviewed</span>
                        </div>          
                        <div class="media-content">
                            <p class="title is-4">{{ research.title|truncatewords:"14" }}</p>
                        </div>
                        <div class="content">
                            {{ research.description|truncatewords:"34" }}
                        </div>
                        <span class="tag is-primary">
                            <a href="{% url 'research:detail' research.id %}" class="has-text-white">read more...</a></span>
                    </div>
        
            {% endfor %}
        {% else %}
            <p>OMG! No research available!</p>
        {% endif %}
    </div>


    <div class="column">
        <h2 class="title is-3">Discover</h2>
            <h4 class="subtitle is-5">studies others haven't seen yet</h4>
            <p>(🛠Coming Soon🛠)</p>
            
            <div class="box">
                    <div class="tags are-medium">
                                
                            <span class="tag is-dark">Example</span>
                            <span class="tag is-warning"> Example </span>
                            <span class="tag is-light">🌳🌲🎋🌴 Plants</span>
                        </div>
                <div class="media-content">
                    <p class="title is-4">title {{ research.title|truncatewords:"14" }}</p>
                    <p class="subtitle is-6">description {{ research.attr }}</p>
                </div>
            </div>

            <div class="box">
                    <div class="tags are-medium">
                                
                            <span class="tag is-link">Example</span>
                            <span class="tag is-danger"> Example </span>
                            <span class="tag is-light">☀️⛅️⛈ Weather</span>
                        </div>
                <div class="media-content">
                    <p class="title is-4">title {{ research.title|truncatewords:"14" }}</p>
                    <p class="subtitle is-6">description {{ research.attr }}</p>
                </div>
            </div>

            <div class="box">
                    <div class="tags are-medium">
                                
                            <span class="tag is-warning">Example</span>
                            <span class="tag is-info"> Example </span>
                            <span class="tag is-light">♻️🌱🍃 Sustainability</span>
                        </div>
                <div class="media-content">
                    <p class="title is-4">title {{ research.title|truncatewords:"14" }}</p>
                    <p class="subtitle is-6">description {{ research.attr }}</p>
                </div>
            </div>

            <div class="box">
                    <div class="tags are-medium">
                                
                            <span class="tag is-black">Example</span>
                            <span class="tag is-success">❕ Featured</span>
                            <span class="tag is-light">💧🌊 Water</span>
                        </div>
                <div class="media-content">
                    <p class="title is-4">research.title {{ research.title }}</p>
                    <p class="subtitle is-6">research.description {{ research.attr }}</p>
                </div>
            </div>

    </div>

            <div class="column">
                    <h2 class="title is-3">Validate</h2>
                    <h4 class="subtitle is-5">inferences made by our community</h4>
                    <p>(🛠Coming Soon🛠)</p>

                </div>
            </div>








{% endblock %}

mysite/research/templates/research/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
    
<a href="{% url 'research:index' %}">More studies?</a>

mysite/research/templates/research/upload.html
{% extends 'base.html' %}
{% block content %}



<h1 class="title is-1">Upload</h1>
<p>(🛠Coming Soon🛠)</p>

<div class="field">
    <div class="file is-large is-boxed has-name">
      <label class="file-label">
        <input class="file-input" type="file" name="resume">
        <span class="file-cta">
          <span class="file-icon">
            <i class="fas fa-upload"></i>
          </span>
          <span class="file-label">
            Find your file
          </span>
        </span>
        <span class="file-name">
          file name shows here
        </span>
      </label>

    
<a href="{% url 'research:upload' %}">Add more?</a>

{% endblock %}

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Statalog - the catalog of data & studies, created by you!</title>
  <link rel="shortcut icon" href="img/logo_primary.png"><!-- Favicon-->
  <link href="https://fonts.googleapis.com/css?family=Nunito:300,500,600" rel="stylesheet">
  <meta property="og:image" content="https://Statalog.com/img/logo.png">
  <meta property="og:url" content="https://Statalog.org/" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="Statalog | the free catalog of data & studies, created by you!" />
  <meta property="og:description" content="Everybody can share data & studies, we all benefit from sharing. Together, we can accomplish more." />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content="@vicki_langer" />
  <meta name="twitter:title" content="Statalog | the free catalog of data & studies, created by you!" />
  <meta name="twitter:description" content="Everybody can share data & studies, we all benefit from sharing. Together, we can accomplish more." />
  <meta name="twitter:image" content="https://Statalog.org/img/logo.png">
  <meta name="author" content="Vicki Langer">
  <meta name="description" content="Invigorating access to reliable case studies, infographics, stats, facts, and figures.">
  <meta name="keywords" content="stats, statistics, data, metrics, case study">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css">
  <script src="https://use.fontawesome.com/644443b801.js"></script>
  <!-- <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script> -->
</head>



<body>

  {% include 'navbar.html' %}

  <main>
    <div class="container has-text-centered">
      {% block content %}
      {% endblock %}
    </div>
  </main>

  {% include 'footer.html' %}
</body>

mysite/templates/footer.html
<footer class="footer">
  <div class="container is-fluid">
    <div class="columns">

      <div class="column">
        <h4>Awesomeness</h4>
        <!--why is this heading acting weird af?!-->
        <ul>
          <li><a href="{{ 'integrations' }}">Integrations</a></li>
          <li><a href="{{ 'how' }}">How To...</a></li>
          <li><a href="{{ 'blog' }}">Blog</a></li>
          <li><a href="{{ 'Dev' }}">Developers Tools</a></li>
        </ul>
      </div>

      <div class="column">
        <h4>Talk To Us</h4>
        <ul>
          <li><a href="{{ 'FAQ' }}"><span class="icon-help"></span> Check the FAQ</a></li>
          <li><a href="mailto:hello@Statalog.Org"><span class="icon-mail"></span> Hello@Statalog.Org</a></li>
          <li><span class="icon-location"></span> 450 Design Ave, WS, NC</li>
        </ul>
      </div>

      <div class="column">
        <h4>Stay Involved</h4>
        <ul>
          <li><a href="{{ 'labs' }}">Labs</a></li>
          <li><a href="https://statalog.slack.com">Chat</a></li>
          <li><a href="{{ 'partners' }}">Partners</a></li>
          <li><a href="https://angel.co/statalog/Jobs">Careers & Jobs</a></li>
        </ul>
        <span class="icon-rss"></span>
      </div>
    </div>

    <div>
      <p class="content has-text-centered"> Statalog - Together, we will accomplish more. © 2019 | <a href="{{ 'about' }}" alt="about us">About Us</a> | <a href="{{ 'legal' }}" alt="privacy policy and terms of use"><span class="icon-lock"></span>Legal Stuff</a></p>
    </div>

</footer>

mysite/templates/navbar.html
<header>
  <nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="{% url 'research:index' %}">
        <img src="https://cdn.worldvectorlogo.com/logos/statalog.svg"> Statalog
        <!--https://Statalog.org/img/logo-primary.png-->
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbar" class="navbar-menu">
      <div class="navbar-start">

        <div class="navbar-item">
          <div class="field">
            <p class="control has-icons-left">
              <input class="input" type="search" placeholder="Search...">
              <span class="icon is-small is-left"><i class="fas fa-search"></i></span>
            </p>
          </div>
        </div>

      </div>

      <div class="navbar-end">

        <div class="buttons">
          <a class="button is-dark" href="{% url 'upload' %}">
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <strong>+</strong>
            <!--to do: get fa icons setup <span class="icon"><i class="fas fa-upload"></i></span>-->
          </a>
          <a class="button is-primary" href="{% url 'signup' %}">
            <strong>Sign up</strong>
          </a>
          <a class="button is-white" href="{% url 'login' %}">
            Log in
          </a>
        </div>

      </div>
    </div>
  </nav>
</header>

mysite/templates/skel.html
{% extends 'base.html' %}
{% block content %}


stuff goes there


{% endblock %}